### PR TITLE
feat(separator): Add in provider option to configure the separator.

### PR DESCRIPTION
**Pull request by admwx7**
Adding in functionality to allow the user to configure the default separator when in the provider stages.

### CODE REVIEW

**Comment by tymondesigns** [comment]
Looks good, thanks

**Comment by admwx7** [comment]
@tymondesigns do you have plans for your next release date?  Just realized I forgot to run gulp and generate the *.js files in dist before you merged.

**Comment by tymondesigns** [comment]
I will probably bump the version tomorrow. I just need to update the docs for this and a few other things.

**Comment by admwx7** [comment]
Sounds good, thanks.

**Comment by tymondesigns** [comment]
`1.1.0` released

**Pull request merged**
