### PR TITLE
Add current value parameter function to put

### PR DESCRIPTION
**Pull request by admwx7**
When passing a function to put, the function will now be called with the currently stored value for the put.  This allows for easily updating values that are stored and depend on the old value, such as adding an item to an array stored in the locker without having to do a get then a put.

Also added in a default parameter option that can be passed, similar to how get works.

### CODE REVIEW

**Comment by tymondesigns** [comment]
this looks great @admwx7. would you be able to rebase your commits, so I can merge?

Thanks

**Comment by admwx7** [comment]
Ha, can't get my rebase to actually squash everything like it should, it just flags more in the commit history.  I went through and did a rebase -i, removed all of your commits, set s for all of mine (removed 2 actually) then set r and updated the commit message for one of the commits.  What am I doing wrong?

**Comment by tymondesigns** [comment]
Assuming you have an `upstream/master` that points to my repo? 
Then you would do `git rebase -i upstream/master` and you should only see your commits and not mine.

**Comment by admwx7** [comment]
Yeah...now I remember why I hate git rebase.  Should be good to go though, want me to make a new PR for it to clean things up?

**Comment by tymondesigns** [comment]
Yea rebase can be PITA sometimes! 

It'll be good to merge for me once Travis has finished. 

Thanks for that!

**Comment by admwx7** [comment]
This code was removed, why?  I'm currently in need of this functionality, and it had no compatibility issues with passing tests.

**Pull request merged**
